CREATE TABLE public.app_invitation (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       character varying(254) NOT NULL,
    token       character varying(128) NOT NULL,
    expiry_date timestamp without time zone NOT NULL,
    date_added  timestamp without time zone DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX app_invitation_token_uk ON public.app_invitation (token);
CREATE INDEX app_invitation_email_index ON public.app_invitation USING btree (email varchar_ops);
